/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajo_3;

/**
 *
 * @author 57321
 */
public class InterfazTrapecio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazTrapecio
     */
    public InterfazTrapecio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Taltura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tbaseh = new javax.swing.JTextField();
        Tdiagonalp = new javax.swing.JTextField();
        Tbasem = new javax.swing.JTextField();
        Tdiagonals = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tresultado = new javax.swing.JTextField();
        btsarea = new javax.swing.JButton();
        btsperimetro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TRAPECIO");

        Taltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TalturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Introduzca el valor de la altura:");

        jLabel3.setText("Introduzca el valor de la base mayor:");

        jLabel4.setText("Introduzca el valor de la base menor:");

        jLabel5.setText("Introduzca el valor de la primer diagonal:");

        jLabel6.setText("Introduzca el valor de la segunda diagonal:");

        Tbaseh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbasehActionPerformed(evt);
            }
        });

        Tdiagonalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdiagonalpActionPerformed(evt);
            }
        });

        Tbasem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbasemActionPerformed(evt);
            }
        });

        Tdiagonals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdiagonalsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Resultado");

        Tresultado.setText("0");
        Tresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresultadoActionPerformed(evt);
            }
        });

        btsarea.setBackground(new java.awt.Color(153, 255, 204));
        btsarea.setText("Calcular Area");
        btsarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsareaActionPerformed(evt);
            }
        });

        btsperimetro.setBackground(new java.awt.Color(153, 255, 204));
        btsperimetro.setText("Calcular Perimetro");
        btsperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsperimetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tbaseh)
                            .addComponent(Tdiagonalp, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(Tbasem, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(Tdiagonals, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(Taltura)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btsarea))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tresultado, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btsperimetro)
                                .addGap(106, 106, 106)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Taltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tbaseh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tbasem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Tdiagonalp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tdiagonals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsarea)
                    .addComponent(btsperimetro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbasehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbasehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbasehActionPerformed

    private void TdiagonalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdiagonalpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdiagonalpActionPerformed

    private void TbasemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbasemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbasemActionPerformed

    private void TdiagonalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdiagonalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdiagonalsActionPerformed

    private void TalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TalturaActionPerformed

    private void TresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TresultadoActionPerformed

    private void btsareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsareaActionPerformed
        double alturaTR,baseH,baseM,diagonalp,diagonals;
        alturaTR=Double.parseDouble(Taltura.getText());
        baseH=Double.parseDouble(Tbaseh.getText());
        baseM=Double.parseDouble(Tbasem.getText());
        diagonalp=Double.parseDouble(Tdiagonalp.getText());
        diagonals=Double.parseDouble(Tdiagonals.getText());
        Trapecio cometa =  new Trapecio(alturaTR,baseH,baseM,diagonalp,diagonals);
        cometa.calcularArea();
        Tresultado.setText(String.valueOf(cometa.calcularArea()));
    }//GEN-LAST:event_btsareaActionPerformed

    private void btsperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsperimetroActionPerformed
       double alturaTR,baseH,baseM,diagonalp,diagonals;
        alturaTR=Double.parseDouble(Taltura.getText());
        baseH=Double.parseDouble(Tbaseh.getText());
        baseM=Double.parseDouble(Tbasem.getText());
        diagonalp=Double.parseDouble(Tdiagonalp.getText());
        diagonals=Double.parseDouble(Tdiagonals.getText());
        Trapecio cometa =  new Trapecio(alturaTR,baseH,baseM,diagonalp,diagonals);
        cometa.calcularPerimetro();
        Tresultado.setText(String.valueOf(cometa.calcularPerimetro()));
    }//GEN-LAST:event_btsperimetroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTrapecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTrapecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTrapecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTrapecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTrapecio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Taltura;
    private javax.swing.JTextField Tbaseh;
    private javax.swing.JTextField Tbasem;
    private javax.swing.JTextField Tdiagonalp;
    private javax.swing.JTextField Tdiagonals;
    private javax.swing.JTextField Tresultado;
    private javax.swing.JButton btsarea;
    private javax.swing.JButton btsperimetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
